/* SPDX-License-Identifier: GPL-2.0-or-later */
#ifndef IPL_DESCRAMBLE_CORE_H
#define IPL_DESCRAMBLE_CORE_H

#include <stddef.h>
#include <stdint.h>

/*
 * segher's GameCube IPL descrambler (BS1 bootrom stream cipher).
 *
 * The IPL body is obfuscated with a data-independent keystream generated by
 * three coupled 16-bit LFSRs. Descrambling is `data[i] ^= keystream[i]`, so
 * the transform is an involution: applying it twice is the identity.
 *
 * Algorithm origin: reversed by Segher Boessenkool (2008). Cross-checked
 * byte-for-byte against the gc-ipl wiki and FIX94/Nintendont ipl.c before
 * vendoring (see README.md). This is a build-time tool, not oracle code.
 */
void ipl_descramble(uint8_t *data, size_t size);

/* IPL image layout. The BS2 load base and file offset below were CORRECTED
 * against the Dolphin oracle (2026-07-09): Dolphin's first boot code executes
 * at guest 0x81200150, which is descrambled file offset 0x250 — so descrambled
 * offset 0x100 maps to guest 0x81200000, and [0,0x100) is the copyright header
 * (an ASCII string, not a DOL header). The earlier 0x820 -> 0x81300000 values
 * (from a third-party summary) were wrong for this IPL and made every absolute
 * pointer land 0x100000 too high. */
#define IPL_SCRAMBLE_START 0x100u      /* first scrambled byte                 */
#define IPL_SCRAMBLE_END   0x1AFF00u   /* one past the last scrambled byte     */
#define IPL_BS2_FILE_OFF   0x100u      /* code image begins here (after (C) hdr)*/
#define IPL_BS2_LOAD_ADDR  0x81200000u /* descrambled 0x100 loads here         */
#define IPL_BS2_ENTRY      0x81200150u /* first instruction Dolphin executes   */

#endif /* IPL_DESCRAMBLE_CORE_H */
