#ifndef IPL_DESCRAMBLE_CORE_H
#define IPL_DESCRAMBLE_CORE_H

#include <stddef.h>
#include <stdint.h>

/*
 * segher's GameCube IPL descrambler (BS1 bootrom stream cipher).
 *
 * The IPL body is obfuscated with a data-independent keystream generated by
 * three coupled 16-bit LFSRs. Descrambling is `data[i] ^= keystream[i]`, so
 * the transform is an involution: applying it twice is the identity.
 *
 * Algorithm origin: reversed by Segher Boessenkool (2008). Cross-checked
 * byte-for-byte against the gc-ipl wiki and FIX94/Nintendont ipl.c before
 * vendoring (see README.md). This is a build-time tool, not oracle code.
 */
void ipl_descramble(uint8_t *data, size_t size);

/* Documented IPL image layout (see README.md). */
#define IPL_SCRAMBLE_START 0x100u      /* first scrambled byte                */
#define IPL_SCRAMBLE_END   0x1AFF00u   /* one past the last scrambled byte    */
#define IPL_BS2_FILE_OFF   0x820u      /* plaintext BS2 begins here (post-de) */
#define IPL_BS2_LOAD_ADDR  0x81300000u /* BS1 copies BS2 here and enters it   */

#endif /* IPL_DESCRAMBLE_CORE_H */
